
services:
  recipes-api:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
